### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-2-entrevista-turisteando-por-mexico#2]
[Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-turisteando-por-mexico/files/12542381/Entrevista.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
